# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NeighborhoodApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NeighborhoodApp
  pod 'Firebase/Firestore'

  target 'NeighborhoodAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NeighborhoodAppUITests' do
    # Pods for testing
  end

end
